import { StrictMode, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, Check, ChevronLeft, ChevronRight, MapPin, Menu, X, Phone, MessageCircle, Mail, Plus } from 'lucide-react';
import { areas, business, reviews, services } from './data';
import { Brand, Heading, Photo, QuoteLink } from './components';
import { QuoteForm } from './QuoteForm';
import './styles.css';

const nav=[['Home','#home'],['Services','#services'],['About','#about'],['Our Work','#work'],['Areas We Serve','#areas'],['Contact','#contact']];
const serviceImages:Record<string,{file:string;alt:string}>={carpets:{file:'newcarpet1.webp',alt:'Carpet extraction cleaning pictured on Cleanest’s original website'},windows:{file:'winc1.webp',alt:'Window being cleaned with a squeegee from Cleanest’s window gallery'},gardens:{file:'newgarden2.webp',alt:'Garden worker trimming a hedge, from Cleanest’s original garden gallery'}};
const gallery=[{file:'newuph1.webp',title:'Carpet care',label:'INTERIOR',alt:'Cleanest worker cleaning a carpet or rug, from the existing Cleanest website'},{file:'newgarden2.webp',title:'Garden maintenance',label:'EXTERIOR',alt:'Hedge trimming pictured on Cleanest’s existing website'},{file:'winc1.webp',title:'Window cleaning',label:'INTERIOR & EXTERIOR',alt:'Glass cleaning with a squeegee, from Cleanest’s service gallery'},{file:'newcarpet1.webp',title:'Deep carpet cleaning',label:'INTERIOR',alt:'Carpet cleaning in progress, from Cleanest’s existing website'}];

function App(){
  const [menuOpen,setMenuOpen]=useState(false);
  const [compactHeader,setCompactHeader]=useState(false);
  const [wideHeader,setWideHeader]=useState(()=>window.innerWidth>=1100);
  const [location,setLocation]=useState('');
  const [service,setService]=useState('');
  const [activePhoto,setActivePhoto]=useState(0);
  const menuButton=useRef<HTMLButtonElement>(null);
  const galleryDialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{
    let frame=0;
    const updateHeader=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{setCompactHeader(window.innerWidth>=768&&window.scrollY>96);setWideHeader(window.innerWidth>=1100);});};
    const goHome=(event:MouseEvent)=>{
      if(event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;
      const link=event.target instanceof Element?event.target.closest('a'):null;
      if(link?.getAttribute('href')==='#home'){
        event.preventDefault();history.pushState(null,'','#home');
        window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
      }
    };
    updateHeader();window.addEventListener('scroll',updateHeader,{passive:true});window.addEventListener('resize',updateHeader);document.addEventListener('click',goHome);
    return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',updateHeader);window.removeEventListener('resize',updateHeader);document.removeEventListener('click',goHome);};
  },[]);
  useEffect(()=>{const handleKey=(event:KeyboardEvent)=>{if(event.key==='Escape'&&menuOpen){setMenuOpen(false);menuButton.current?.focus();}if(galleryDialog.current?.open){if(event.key==='ArrowRight'){event.preventDefault();setActivePhoto(value=>(value+1)%gallery.length);}if(event.key==='ArrowLeft'){event.preventDefault();setActivePhoto(value=>(value+gallery.length-1)%gallery.length);}}};window.addEventListener('keydown',handleKey);return()=>window.removeEventListener('keydown',handleKey);},[menuOpen]);
  function openPhoto(index:number){setActivePhoto(index);galleryDialog.current?.showModal();}
  return <><a href="#main" className="skip-link">Skip to content</a><div className="header-shell"><header className={`masthead ${compactHeader?'is-compact':''}`}><div className="header-identity" inert={compactHeader && wideHeader ? true : undefined}><div className="frame identity-row"><Brand/><div className="header-location"><MapPin size={15}/><span>JOHANNESBURG<br/>PLETTENBERG BAY</span></div><a className="header-phone" href={`tel:${business.tel}`}><Phone size={16}/>{business.phone}</a><QuoteLink className="header-quote"/><button ref={menuButton} className="menu-toggle" aria-label={menuOpen?'Close navigation':'Open navigation'} aria-expanded={menuOpen} aria-controls="navigation" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button></div></div><nav id="navigation" className={menuOpen?'open':''} aria-label="Main navigation"><div className="frame nav-inner"><div className="compact-brand"><Brand/></div><span className="nav-caption">PROFESSIONAL PROPERTY CARE</span><div>{nav.map(([name,href])=><a href={href} key={href} onClick={()=>setMenuOpen(false)}>{name}</a>)}<a className="nav-whatsapp" href={business.whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={15}/>WhatsApp us</a></div><QuoteLink className="compact-quote"/></div></nav></header></div>
  <main id="main"><section className="hero" id="home"><div className="frame"><div className="hero-intro"><div className="hero-title"><p className="eyebrow">CLEANEST · CLEANING & GARDEN CARE</p><h1><span>Professional<span className="mobile-break"><br/></span> care.</span><span>Inside and out.</span></h1></div><div className="hero-details"><div className="hero-years"><strong>29</strong><span>YEARS OF<br/>EXPERIENCE</span></div><p>Professional cleaning and garden care for homes and businesses. Owner managed, with local teams in Johannesburg and Plettenberg Bay.</p><div className="hero-actions"><QuoteLink/><a href="#services" className="explore-link">Explore Services<ArrowRight size={18}/></a></div></div></div><figure className="hero-image"><Photo file="newgarden1.webp" alt="Cleanest garden maintenance team working on a coastal lawn, pictured on the existing Cleanest website" priority/><figcaption><span>CARE FOR YOUR PROPERTY, INSIDE & OUTSIDE</span><span>JOHANNESBURG / PLETTENBERG BAY</span></figcaption></figure></div></section>
  <div className="property-strip"><div className="frame"><span>Homes & offices</span><span>Complexes & estates</span><span>Corporate grounds</span><span>Holiday homes & guest houses</span></div></div>
  <section className="section frame" id="services"><Heading label="01 / OUR SERVICES" title="Considered care. Every space.">Cleaning and garden services for the interiors you use and the grounds that surround them.</Heading><div className="service-directory">{services.map((item,index)=><article id={item.id} className="service-row" key={item.id}><span className="service-index">0{index+1}</span><div className="service-description"><h3>{item.name}</h3><p>{item.description}</p><a className="service-enquiry" href="#contact" onClick={()=>setService(item.name)}>Request a Quote<ArrowUpRight size={17}/></a></div><ul>{item.details.map(detail=><li key={detail}><Check size={14}/>{detail}</li>)}</ul><Photo file={serviceImages[item.id].file} alt={serviceImages[item.id].alt}/></article>)}</div><p className="services-note">Garden maintenance also serves golf estates, schools and sports fields. <a href="#contact" onClick={()=>setService('Garden services')}>Discuss your requirements<ArrowUpRight size={16}/></a></p></section>
  <section className="about-section" id="about"><div className="section frame"><div className="about-intro"><div><p className="eyebrow">02 / THE PEOPLE BEHIND THE CARE</p><h2>Established experience.<br/>Personal attention.</h2></div><div><p>Cleanest brings cleaning and garden care together, with dedicated local teams in Johannesburg and Plettenberg Bay.</p><p>Owner management means personal attention to every project, from homes and offices to complexes, estates and corporate gardens.</p><QuoteLink className="cta-navy"/></div></div><figure className="team-image"><Photo file="carpetteam.webp" alt="Team photograph from Cleanest’s website, showing staff in branded workwear beside company vehicles"/><figcaption><span>THE CLEANEST TEAM</span><span>Photograph from Cleanest’s existing website</span></figcaption></figure><div className="about-values"><div><span>THE APPROACH</span><strong>Owner managed</strong><p>Personal attention to your property.</p></div><div><span>THE SCOPE</span><strong>Inside and outside</strong><p>Cleaning and year-round garden care.</p></div><div><span>THE PRESENCE</span><strong>Johannesburg & Plett</strong><p>Local teams in both service areas.</p></div></div></div></section>
  <section className="section frame" id="work"><Heading label="03 / CLEANEST IN PRACTICE" title="Care, seen in the details.">Cleaning and garden photographs from Cleanest’s existing website. Select an image for a closer look.</Heading><div className="gallery-grid">{gallery.map((photo,index)=><figure key={photo.file}><button className="gallery-open" onClick={()=>openPhoto(index)} aria-label={`View ${photo.title.toLowerCase()} photograph`}><Photo file={photo.file} alt={photo.alt}/><span className="gallery-zoom"><Plus size={19}/></span></button><figcaption><span>{photo.label}</span><strong>{photo.title}</strong><small>0{index+1}</small></figcaption></figure>)}</div></section>
  <section className="areas-section" id="areas"><div className="section frame"><Heading label="04 / AREAS WE SERVE" title="Local knowledge. Two locations.">Choose your location to prepare an enquiry for the care your property needs.</Heading><div className="area-directory">{areas.map((area,index)=><article className="area-row" key={area.name}><div className="area-name"><span>0{index+1} / {area.label}</span><h3>{area.name}</h3><a href="#contact" onClick={()=>setLocation(area.name)}>Request a Quote<ArrowUpRight size={17}/></a></div><div className="area-information"><p>{area.description}</p><ul aria-label={`${area.name} service areas`}>{area.suburbs.split(' · ').map(suburb=><li key={suburb}>{suburb}</li>)}</ul><a href="#contact" onClick={()=>setLocation(area.name)}>Ask about your suburb<ArrowRight size={16}/></a></div></article>)}</div></div></section>
  <section className="section frame testimonials" id="reviews"><p className="eyebrow">05 / CLIENT PERSPECTIVES</p><div className="testimonials-layout"><h2>Care that<br/>speaks for itself.</h2>{reviews.map(review=><figure className="testimonial" key={review.name}><span className="quote-symbol" aria-hidden="true">“</span><blockquote>{review.quote}</blockquote><figcaption><div><strong>{review.name}</strong><span>{review.area}</span></div><a href={review.source} target="_blank" rel="noreferrer" aria-label={`Source testimonial for ${review.name}`}><ArrowUpRight size={17}/></a></figcaption></figure>)}</div></section>
  <section className="contact-section" id="contact"><div className="section frame contact-layout"><div className="contact-copy"><p className="eyebrow">06 / REQUEST A QUOTE</p><h2>Let’s take care<br/>of your property.</h2><p>Tell us about the work required. Select your location and service, and share the details of your space.</p><div className="contact-links"><a className="contact-phone" href={`tel:${business.tel}`}><Phone size={19}/>{business.phone}</a>{business.emails.map(email=><a href={`mailto:${email}`} key={email}><Mail size={17}/>{email}</a>)}<a className="contact-whatsapp" href={business.whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={18}/>Enquire on WhatsApp<ArrowUpRight size={16}/></a></div><p className="contact-hours">Monday–Friday · 08h00–17h00</p></div><QuoteForm location={location} setLocation={setLocation} service={service} setService={setService}/></div></section></main>
  <footer><div className="frame footer-main"><div className="footer-brand"><Brand/><p>Professional cleaning & garden care.<br/>Johannesburg & Plettenberg Bay.</p></div><div><h3>Explore</h3>{nav.slice(1).map(([name,href])=><a href={href} key={href}>{name}</a>)}</div><div><h3>Our services</h3>{services.map(item=><a href={`#${item.id}`} key={item.id}>{item.name}</a>)}</div><div><h3>Connect</h3><a href={`tel:${business.tel}`}>{business.phone}</a>{business.emails.map(email=><a href={`mailto:${email}`} key={email}>{email}</a>)}<a href={business.facebook} target="_blank" rel="noreferrer" className="footer-social">Facebook<ArrowUpRight size={15}/></a></div></div><div className="frame footer-bottom"><span>© {new Date().getFullYear()} Cleanest. All rights reserved.</span><span>JOHANNESBURG / PLETTENBERG BAY</span><a href="#home">Back to top<ArrowRight size={14}/></a></div></footer>
  <dialog ref={galleryDialog} className="gallery-dialog"><div className="gallery-dialog-top"><span>CLEANEST / PHOTOGRAPHIC GALLERY</span><button onClick={()=>galleryDialog.current?.close()} aria-label="Close gallery"><X/></button></div><Photo file={gallery[activePhoto].file} alt={gallery[activePhoto].alt}/><div className="gallery-dialog-bottom"><div><strong>{gallery[activePhoto].title}</strong><span>From Cleanest’s existing website</span></div><div><button aria-label="Previous photograph" onClick={()=>setActivePhoto((activePhoto+gallery.length-1)%gallery.length)}><ChevronLeft/></button><span>{activePhoto+1} / {gallery.length}</span><button aria-label="Next photograph" onClick={()=>setActivePhoto((activePhoto+1)%gallery.length)}><ChevronRight/></button></div></div></dialog></>;
}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);



